"""initial_schema_phase2

Revision ID: 3a994b110de2
Revises: 
Create Date: 2026-09-01 09:53:58.972605

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3a994b110de2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ai_recommendations', 'status',
               existing_type=postgresql.ENUM('PENDING', 'APPROVED', 'REJECTED', name='recommendation_status'),
               comment=None,
               existing_comment='PENDING until an operator acts. AI never autonomously changes to APPROVED.',
               existing_nullable=False,
               existing_server_default=sa.text("'PENDING'::recommendation_status"))
    op.drop_index(op.f('idx_rec_created'), table_name='ai_recommendations')
    op.drop_index(op.f('idx_rec_junction'), table_name='ai_recommendations')
    op.drop_index(op.f('idx_rec_severity'), table_name='ai_recommendations')
    op.drop_index(op.f('idx_rec_status'), table_name='ai_recommendations')
    op.create_index(op.f('ix_ai_recommendations_created_at'), 'ai_recommendations', ['created_at'], unique=False)
    op.create_index(op.f('ix_ai_recommendations_id'), 'ai_recommendations', ['id'], unique=False)
    op.create_index(op.f('ix_ai_recommendations_junction_id'), 'ai_recommendations', ['junction_id'], unique=False)
    op.create_index(op.f('ix_ai_recommendations_status'), 'ai_recommendations', ['status'], unique=False)
    op.drop_table_comment(
        'ai_recommendations',
        existing_comment='AI-generated signal timing suggestions. MUST be approved by a human operator before any action is taken.',
        schema=None
    )
    op.drop_index(op.f('idx_er_auth'), table_name='emergency_routes')
    op.drop_index(op.f('idx_er_created'), table_name='emergency_routes')
    op.drop_index(op.f('idx_er_status'), table_name='emergency_routes')
    op.create_index(op.f('ix_emergency_routes_id'), 'emergency_routes', ['id'], unique=False)
    op.create_index(op.f('ix_emergency_routes_status'), 'emergency_routes', ['status'], unique=False)
    op.drop_table_comment(
        'emergency_routes',
        existing_comment='Emergency green-wave corridor requests. Operator authorization required before activation.',
        schema=None
    )
    op.alter_column('junctions', 'junction_code',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='Short unique identifier, e.g. J-101',
               existing_nullable=False)
    op.alter_column('junctions', 'traffic_density',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Current congestion percentage (0-100)',
               existing_nullable=True)
    op.drop_index(op.f('idx_junctions_code'), table_name='junctions')
    op.drop_index(op.f('idx_junctions_status'), table_name='junctions')
    op.drop_constraint(op.f('junctions_junction_code_key'), 'junctions', type_='unique')
    op.create_index(op.f('ix_junctions_id'), 'junctions', ['id'], unique=False)
    op.create_index(op.f('ix_junctions_junction_code'), 'junctions', ['junction_code'], unique=True)
    op.drop_table_comment(
        'junctions',
        existing_comment='Monitored road intersections with traffic signals',
        schema=None
    )
    op.drop_index(op.f('idx_log_action'), table_name='operator_logs')
    op.drop_index(op.f('idx_log_created'), table_name='operator_logs')
    op.drop_index(op.f('idx_log_user'), table_name='operator_logs')
    op.create_index(op.f('ix_operator_logs_action'), 'operator_logs', ['action'], unique=False)
    op.create_index(op.f('ix_operator_logs_created_at'), 'operator_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_operator_logs_id'), 'operator_logs', ['id'], unique=False)
    op.create_index(op.f('ix_operator_logs_user_id'), 'operator_logs', ['user_id'], unique=False)
    op.drop_table_comment(
        'operator_logs',
        existing_comment='Immutable audit trail. Every significant operator action is recorded here for accountability. Do not delete rows.',
        schema=None
    )
    op.drop_index(op.f('idx_signal_changed'), table_name='signal_timings')
    op.drop_index(op.f('idx_signal_junction'), table_name='signal_timings')
    op.create_index(op.f('ix_signal_timings_changed_at'), 'signal_timings', ['changed_at'], unique=False)
    op.create_index(op.f('ix_signal_timings_id'), 'signal_timings', ['id'], unique=False)
    op.create_index(op.f('ix_signal_timings_junction_id'), 'signal_timings', ['junction_id'], unique=False)
    op.drop_table_comment(
        'signal_timings',
        existing_comment='Audit trail of every signal timing change. Operator must explicitly approve before entry is created.',
        schema=None
    )
    op.drop_index(op.f('idx_traffic_junction'), table_name='traffic_records')
    op.drop_index(op.f('idx_traffic_level'), table_name='traffic_records')
    op.drop_index(op.f('idx_traffic_recorded'), table_name='traffic_records')
    op.create_index(op.f('ix_traffic_records_id'), 'traffic_records', ['id'], unique=False)
    op.create_index(op.f('ix_traffic_records_junction_id'), 'traffic_records', ['junction_id'], unique=False)
    op.create_index(op.f('ix_traffic_records_recorded_at'), 'traffic_records', ['recorded_at'], unique=False)
    op.drop_table_comment(
        'traffic_records',
        existing_comment='Time-series traffic observations at each junction. Kaggle dataset will populate this table in Phase 3.',
        schema=None
    )
    op.alter_column('users', 'password_hash',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='Bcrypt hash — plaintext passwords are never stored',
               existing_nullable=False)
    op.alter_column('users', 'district',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='City district this operator is assigned to',
               existing_nullable=True)
    op.drop_index(op.f('idx_users_email'), table_name='users')
    op.drop_index(op.f('idx_users_role'), table_name='users')
    op.drop_index(op.f('idx_users_status'), table_name='users')
    op.drop_constraint(op.f('users_email_key'), 'users', type_='unique')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.drop_table_comment(
        'users',
        existing_comment='Authorized personnel who operate the SignalAI platform',
        schema=None
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table_comment(
        'users',
        'Authorized personnel who operate the SignalAI platform',
        existing_comment=None,
        schema=None
    )
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_users_status'), 'users', ['status'], unique=False)
    op.create_index(op.f('idx_users_role'), 'users', ['role'], unique=False)
    op.create_index(op.f('idx_users_email'), 'users', ['email'], unique=False)
    op.alter_column('users', 'district',
               existing_type=sa.VARCHAR(length=100),
               comment='City district this operator is assigned to',
               existing_nullable=True)
    op.alter_column('users', 'password_hash',
               existing_type=sa.VARCHAR(length=255),
               comment='Bcrypt hash — plaintext passwords are never stored',
               existing_nullable=False)
    op.create_table_comment(
        'traffic_records',
        'Time-series traffic observations at each junction. Kaggle dataset will populate this table in Phase 3.',
        existing_comment=None,
        schema=None
    )
    op.drop_index(op.f('ix_traffic_records_recorded_at'), table_name='traffic_records')
    op.drop_index(op.f('ix_traffic_records_junction_id'), table_name='traffic_records')
    op.drop_index(op.f('ix_traffic_records_id'), table_name='traffic_records')
    op.create_index(op.f('idx_traffic_recorded'), 'traffic_records', [sa.literal_column('recorded_at DESC')], unique=False)
    op.create_index(op.f('idx_traffic_level'), 'traffic_records', ['traffic_level'], unique=False)
    op.create_index(op.f('idx_traffic_junction'), 'traffic_records', ['junction_id'], unique=False)
    op.create_table_comment(
        'signal_timings',
        'Audit trail of every signal timing change. Operator must explicitly approve before entry is created.',
        existing_comment=None,
        schema=None
    )
    op.drop_index(op.f('ix_signal_timings_junction_id'), table_name='signal_timings')
    op.drop_index(op.f('ix_signal_timings_id'), table_name='signal_timings')
    op.drop_index(op.f('ix_signal_timings_changed_at'), table_name='signal_timings')
    op.create_index(op.f('idx_signal_junction'), 'signal_timings', ['junction_id'], unique=False)
    op.create_index(op.f('idx_signal_changed'), 'signal_timings', [sa.literal_column('changed_at DESC')], unique=False)
    op.create_table_comment(
        'operator_logs',
        'Immutable audit trail. Every significant operator action is recorded here for accountability. Do not delete rows.',
        existing_comment=None,
        schema=None
    )
    op.drop_index(op.f('ix_operator_logs_user_id'), table_name='operator_logs')
    op.drop_index(op.f('ix_operator_logs_id'), table_name='operator_logs')
    op.drop_index(op.f('ix_operator_logs_created_at'), table_name='operator_logs')
    op.drop_index(op.f('ix_operator_logs_action'), table_name='operator_logs')
    op.create_index(op.f('idx_log_user'), 'operator_logs', ['user_id'], unique=False)
    op.create_index(op.f('idx_log_created'), 'operator_logs', [sa.literal_column('created_at DESC')], unique=False)
    op.create_index(op.f('idx_log_action'), 'operator_logs', ['action'], unique=False)
    op.create_table_comment(
        'junctions',
        'Monitored road intersections with traffic signals',
        existing_comment=None,
        schema=None
    )
    op.drop_index(op.f('ix_junctions_junction_code'), table_name='junctions')
    op.drop_index(op.f('ix_junctions_id'), table_name='junctions')
    op.create_unique_constraint(op.f('junctions_junction_code_key'), 'junctions', ['junction_code'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_junctions_status'), 'junctions', ['status'], unique=False)
    op.create_index(op.f('idx_junctions_code'), 'junctions', ['junction_code'], unique=False)
    op.alter_column('junctions', 'traffic_density',
               existing_type=sa.INTEGER(),
               comment='Current congestion percentage (0-100)',
               existing_nullable=True)
    op.alter_column('junctions', 'junction_code',
               existing_type=sa.VARCHAR(length=20),
               comment='Short unique identifier, e.g. J-101',
               existing_nullable=False)
    op.create_table_comment(
        'emergency_routes',
        'Emergency green-wave corridor requests. Operator authorization required before activation.',
        existing_comment=None,
        schema=None
    )
    op.drop_index(op.f('ix_emergency_routes_status'), table_name='emergency_routes')
    op.drop_index(op.f('ix_emergency_routes_id'), table_name='emergency_routes')
    op.create_index(op.f('idx_er_status'), 'emergency_routes', ['status'], unique=False)
    op.create_index(op.f('idx_er_created'), 'emergency_routes', [sa.literal_column('created_at DESC')], unique=False)
    op.create_index(op.f('idx_er_auth'), 'emergency_routes', ['authorization_status'], unique=False)
    op.create_table_comment(
        'ai_recommendations',
        'AI-generated signal timing suggestions. MUST be approved by a human operator before any action is taken.',
        existing_comment=None,
        schema=None
    )
    op.drop_index(op.f('ix_ai_recommendations_status'), table_name='ai_recommendations')
    op.drop_index(op.f('ix_ai_recommendations_junction_id'), table_name='ai_recommendations')
    op.drop_index(op.f('ix_ai_recommendations_id'), table_name='ai_recommendations')
    op.drop_index(op.f('ix_ai_recommendations_created_at'), table_name='ai_recommendations')
    op.create_index(op.f('idx_rec_status'), 'ai_recommendations', ['status'], unique=False)
    op.create_index(op.f('idx_rec_severity'), 'ai_recommendations', ['severity'], unique=False)
    op.create_index(op.f('idx_rec_junction'), 'ai_recommendations', ['junction_id'], unique=False)
    op.create_index(op.f('idx_rec_created'), 'ai_recommendations', [sa.literal_column('created_at DESC')], unique=False)
    op.alter_column('ai_recommendations', 'status',
               existing_type=postgresql.ENUM('PENDING', 'APPROVED', 'REJECTED', name='recommendation_status'),
               comment='PENDING until an operator acts. AI never autonomously changes to APPROVED.',
               existing_nullable=False,
               existing_server_default=sa.text("'PENDING'::recommendation_status"))
    # ### end Alembic commands ###
